name: Health Check
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Test azure
    runs-on: ubuntu-latest
    steps:
    - name: Create an Azure DevOps Bug Workitem when a workflow fails
      uses: stefanstranger/azuredevops-bug-action@1.1
      with:
        OrganizationName: "MWO-MFSW"
        PAT: "PAT"
        ProjectName: "MWO_Lab_1_Exercises_2"
        AreaPath: "MWO_Lab_1_Exercises_2"
        IterationPath: "MWO_Lab_1_Exercises_2"
        GithubToken: "GithubToken"
        WorkflowFileName: "blank.yml"
      env:
        PAT: ${{ secrets.PAT }}
        GithubToken: ${{ secrets.githubtoken }}
